### ISSUE TITLE
add new maintainer to this repo

### ISSUE THREAD

**Issue by lwasser** [conda-forge/earthpy-feedstock#15]
hi @ocefpaf / conda forge colleagues. Can we please add @nkorinek as a maintainer for this repo? i am not sure how to do that. many thanks

**Comment by ocefpaf** [comment]
@conda-forge-admin, please add user @nkorinek

**Comment by ocefpaf** [comment]
@lwasser https://github.com/conda-forge/earthpy-feedstock/issues/15#issuecomment-931605110 should trigger a PR and the current maintainer can merge it to add the new person.

**Comment by lwasser** [comment]
@ocefpaf THANK YOU so so much. i will look for the PR and will merge it.

**Comment by ocefpaf** [comment]
> @ocefpaf THANK YOU so so much. i will look for the PR and will merge it.

The webservice may be slow. If you are in a hurry you can send a PR to add the new person's GitHub handle here:

https://github.com/conda-forge/earthpy-feedstock/blob/master/recipe/meta.yaml#L56-L59

**Comment by ocefpaf** [comment]
OK. Looks like I need to do that from a new issue. See https://github.com/conda-forge/earthpy-feedstock/issues/16 and #17

**Comment by lwasser** [comment]
closing this as i just merged #17 ! many thanks!!
